"""General sequential k-nearest-neighbor tabular synthesizer.

Schema-agnostic: types come from dtypes and cardinality only.  No domain
column names are special-cased.  The optional targets ``y`` and
``y_class`` (when present and ``include_targets=True``) are visited last
so they condition on the already-synthesized feature vector.

Algorithm
---------
1. The first visited column is drawn from its empirical distribution.
2. Each later column is generated by encoding the already-synthesized
   previous columns, querying ``sklearn.neighbors.NearestNeighbors``
   fitted on the same encoding of the training rows, and drawing the
   next value from those ``k`` neighbors.  Continuous columns may add
   Gaussian jitter (scale = ``jitter`` × local neighbor std, falling
   back to the column std when the neighborhood is degenerate).

API
---
* ``KNNConditionalSynthesizer.fit(df, include_targets=True, n_neighbors=15)``
* ``KNNConditionalSynthesizer.sample(n, seed)``
* ``synthesize_knn(df, n=None, seed=0, include_targets=True)``

Failure modes
-------------
* **Curse of dimensionality.**  Euclidean distance on the encoded
  previous-column space concentrates as more columns are visited:
  neighbor distances become nearly identical, so the "local" conditional
  collapses toward a near-marginal draw.  Wide tables therefore lose
  higher-order dependence in later columns — including targets placed
  last.  This is the dominant failure of sequential kNN, not a tuning
  bug.
* Small ``n`` relative to ``k``: almost every query shares the same
  neighbor set and conditionals oversmooth.
* ``jitter=0`` on continuous columns (and any discrete column): donors
  are copied verbatim — a privacy / uniqueness leak.
* High-cardinality categoricals encoded as scaled integer codes are
  treated as ordinal; Hamming geometry is only approximate.
* Missingness is median/mode-imputed in the feature space, so MAR
  patterns are not modeled.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd
from sklearn.neighbors import NearestNeighbors

TARGET_COLS: tuple[str, ...] = ("y", "y_class")

# Integer cardinality at or below this (and ≤ 10% of n) stays discrete.
_LOW_CARD_CAP = 15
_SCALE_FLOOR = 1e-12


def _is_bool_dtype(dtype: Any) -> bool:
    return pd.api.types.is_bool_dtype(dtype)


def _is_na(v: Any) -> bool:
    if v is None:
        return True
    try:
        return bool(pd.isna(v))
    except (ValueError, TypeError):
        return False


def _unique_dropna(s: pd.Series) -> np.ndarray:
    return pd.unique(s.dropna())


def _is_zero_one(s: pd.Series) -> bool:
    """True when every non-null value is in {0, 1} (int, float, or bool)."""
    vals = _unique_dropna(s)
    if vals.size == 0 or vals.size > 2:
        return False
    for v in vals:
        if isinstance(v, (bool, np.bool_)):
            continue
        try:
            fv = float(v)
        except (TypeError, ValueError):
            return False
        if fv not in (0.0, 1.0) or not np.isfinite(fv):
            return False
    return True


def _is_categorical_series(s: pd.Series, n: int) -> bool:
    """Infer categorical / binary vs numeric from dtype and cardinality only."""
    dtype = s.dtype
    if _is_bool_dtype(dtype):
        return True
    if isinstance(dtype, pd.CategoricalDtype):
        return True
    if pd.api.types.is_object_dtype(dtype) or pd.api.types.is_string_dtype(dtype):
        return True
    if pd.api.types.is_datetime64_any_dtype(dtype) or pd.api.types.is_timedelta64_dtype(
        dtype
    ):
        return False
    if not pd.api.types.is_numeric_dtype(dtype):
        return True
    if _is_zero_one(s):
        return True
    if pd.api.types.is_integer_dtype(dtype):
        nunique = int(s.nunique(dropna=True))
        return nunique <= min(_LOW_CARD_CAP, max(2, int(0.10 * n)))
    return False


def _visit_order(columns: list[str], include_targets: bool) -> list[str]:
    """Given order, with ``y`` / ``y_class`` appended last when present."""
    cols = list(columns)
    if not include_targets:
        cols = [c for c in cols if c not in TARGET_COLS]
    present_targets = [c for c in TARGET_COLS if c in cols]
    if present_targets:
        rest = [c for c in cols if c not in TARGET_COLS]
        return rest + present_targets
    return cols


def _is_bool_like(cats: pd.Index) -> bool:
    if len(cats) == 0:
        return False
    return all(isinstance(v, (bool, np.bool_)) for v in cats)


def _category_code(value: Any, cats: pd.Index) -> int:
    for i, c in enumerate(cats):
        if c == value:
            return i
    return -1


@dataclass
class _FirstStep:
    column: str
    values: np.ndarray


@dataclass
class _NNStep:
    column: str
    predictors: list[str]
    nn: NearestNeighbors
    values: np.ndarray
    kind: str
    y_std: float


@dataclass
class _ConstStep:
    column: str
    value: Any
    kind: str


_Step = _FirstStep | _NNStep | _ConstStep


def _fit_nn(X: np.ndarray, k: int) -> tuple[NearestNeighbors, int]:
    n_obs = int(X.shape[0])
    k_eff = max(1, min(int(k), n_obs))
    nn = NearestNeighbors(n_neighbors=k_eff, algorithm="auto", metric="euclidean")
    nn.fit(X)
    return nn, k_eff


class KNNConditionalSynthesizer:
    """Sequential kNN synthesizer (empirical first column, donor later ones)."""

    def __init__(self) -> None:
        self.include_targets_: bool | None = None
        self.n_neighbors_: int | None = None
        self.jitter_: float = 0.25
        self.column_order_: list[str] = []
        self.output_columns_: list[str] = []
        self.kinds_: dict[str, str] = {}
        self.dtypes_: dict[str, Any] = {}
        self.cat_categories_: dict[str, pd.Index] = {}
        self.cat_fill_: dict[str, Any] = {}
        self.num_fill_: dict[str, float] = {}
        self.num_mean_: dict[str, float] = {}
        self.num_scale_: dict[str, float] = {}
        self.cat_mean_: dict[str, float] = {}
        self.cat_scale_: dict[str, float] = {}
        self.steps_: list[_Step] = []
        self.n_train_: int = 0

    def fit(
        self,
        df: pd.DataFrame,
        include_targets: bool = True,
        n_neighbors: int = 15,
        jitter: float = 0.25,
    ) -> KNNConditionalSynthesizer:
        if not isinstance(df, pd.DataFrame):
            raise TypeError("df must be a pandas DataFrame")
        if df.empty:
            raise ValueError("df must contain at least one row")
        k = int(n_neighbors)
        if k < 1:
            raise ValueError("n_neighbors must be >= 1")

        work = df.copy()
        if not include_targets:
            drop = [c for c in TARGET_COLS if c in work.columns]
            work = work.drop(columns=drop)

        n = len(work)
        kinds = {
            c: "cat" if _is_categorical_series(work[c], n) else "num"
            for c in work.columns
        }
        order = _visit_order(list(work.columns), include_targets=True)

        self.include_targets_ = bool(include_targets)
        self.n_neighbors_ = k
        self.jitter_ = float(jitter)
        self.column_order_ = list(order)
        self.output_columns_ = [c for c in work.columns]
        self.kinds_ = kinds
        self.dtypes_ = {c: work[c].dtype for c in work.columns}
        self.cat_categories_ = {}
        self.cat_fill_ = {}
        self.num_fill_ = {}
        self.num_mean_ = {}
        self.num_scale_ = {}
        self.cat_mean_ = {}
        self.cat_scale_ = {}
        self.steps_ = []
        self.n_train_ = n

        for col, kind in kinds.items():
            s = work[col]
            if kind == "cat":
                cats = pd.Index(_unique_dropna(s))
                self.cat_categories_[col] = cats
                mode = s.mode(dropna=True)
                if len(mode):
                    self.cat_fill_[col] = mode.iloc[0]
                elif len(cats):
                    self.cat_fill_[col] = cats[0]
                else:
                    self.cat_fill_[col] = None
                codes = self._encode_categorical(s, col)
                self.cat_mean_[col] = float(np.mean(codes)) if codes.size else 0.0
                sc = float(np.std(codes)) if codes.size else 0.0
                self.cat_scale_[col] = sc if sc > _SCALE_FLOOR else 1.0
            else:
                numeric = pd.to_numeric(s, errors="coerce")
                med = numeric.median()
                fill = float(med) if pd.notna(med) else 0.0
                self.num_fill_[col] = fill
                filled = numeric.fillna(fill).to_numpy(dtype=float)
                finite = filled[np.isfinite(filled)]
                if finite.size:
                    self.num_mean_[col] = float(np.mean(finite))
                    sc = float(np.std(finite))
                else:
                    self.num_mean_[col] = 0.0
                    sc = 0.0
                self.num_scale_[col] = sc if sc > _SCALE_FLOOR else 1.0

        for i, col in enumerate(order):
            y = work[col]
            observed = y.notna()
            if not observed.any():
                fill = (
                    self.cat_fill_.get(col)
                    if kinds[col] == "cat"
                    else self.num_fill_.get(col, 0.0)
                )
                self.steps_.append(_ConstStep(column=col, value=fill, kind=kinds[col]))
                continue

            y_obs = y.loc[observed]
            n_unique = int(y_obs.nunique(dropna=True))
            if n_unique <= 1:
                self.steps_.append(
                    _ConstStep(column=col, value=y_obs.iloc[0], kind=kinds[col])
                )
                continue

            if i == 0:
                self.steps_.append(_FirstStep(column=col, values=y_obs.to_numpy()))
                continue

            predictors = order[:i]
            X = self._encode_block(work.loc[observed], predictors)
            if kinds[col] == "cat":
                y_arr = y_obs.to_numpy()
                finite_rows = np.ones(len(y_arr), dtype=bool)
                y_fit: np.ndarray = y_arr
                y_std = 0.0
            else:
                y_num = pd.to_numeric(y_obs, errors="coerce").to_numpy(dtype=float)
                finite_rows = np.isfinite(y_num)
                if int(finite_rows.sum()) <= 1:
                    val = float(y_num[finite_rows][0]) if finite_rows.any() else 0.0
                    self.steps_.append(_ConstStep(column=col, value=val, kind="num"))
                    continue
                y_fit = y_num[finite_rows]
                y_std = float(np.std(y_fit))
                if not np.isfinite(y_std):
                    y_std = 0.0

            X_fit = X[finite_rows]
            if X_fit.shape[0] == 0:
                fill = (
                    self.cat_fill_.get(col)
                    if kinds[col] == "cat"
                    else self.num_fill_.get(col, 0.0)
                )
                self.steps_.append(_ConstStep(column=col, value=fill, kind=kinds[col]))
                continue

            nn, _k_eff = _fit_nn(X_fit, k)
            self.steps_.append(
                _NNStep(
                    column=col,
                    predictors=predictors,
                    nn=nn,
                    values=y_fit,
                    kind=kinds[col],
                    y_std=y_std,
                )
            )
        return self

    def sample(self, n: int, seed: int | None = None) -> pd.DataFrame:
        if not self.steps_ and not self.output_columns_:
            return pd.DataFrame(index=range(int(n)))
        if not self.column_order_:
            raise RuntimeError("KNNConditionalSynthesizer.fit() must be called first")
        n = int(n)
        if n < 0:
            raise ValueError("n must be non-negative")
        if n == 0:
            return pd.DataFrame(
                {c: pd.Series(dtype=self.dtypes_[c]) for c in self.output_columns_}
            )
        rng = np.random.default_rng(seed)
        syn: dict[str, np.ndarray] = {}

        for step in self.steps_:
            if isinstance(step, _ConstStep):
                syn[step.column] = np.full(n, step.value, dtype=object)
                continue
            if isinstance(step, _FirstStep):
                idx = rng.integers(0, len(step.values), size=n)
                syn[step.column] = step.values[idx]
                continue

            prev = pd.DataFrame({c: syn[c] for c in step.predictors})
            X = self._encode_block(prev, step.predictors)
            syn[step.column] = self._draw_from_neighbors(rng, step, X, n)

        data: dict[str, Any] = {}
        for col in self.output_columns_:
            data[col] = self._cast_column(col, syn[col])
        return pd.DataFrame(data, index=range(n))

    def _draw_from_neighbors(
        self,
        rng: np.random.Generator,
        step: _NNStep,
        X: np.ndarray,
        n: int,
    ) -> np.ndarray:
        _dist, indices = step.nn.kneighbors(X)
        k = int(indices.shape[1])
        pick = rng.integers(0, k, size=n)
        chosen = indices[np.arange(n), pick]
        drawn = step.values[chosen]
        if step.kind != "num" or self.jitter_ <= 0:
            return drawn

        neighbor_vals = np.asarray(step.values[indices], dtype=float)
        loc_std = np.std(neighbor_vals, axis=1)
        fallback = step.y_std if step.y_std > _SCALE_FLOOR else 0.0
        scale = np.where(loc_std > _SCALE_FLOOR, loc_std, fallback)
        noise = rng.normal(0.0, self.jitter_ * scale, size=n)
        out = np.asarray(drawn, dtype=float) + noise
        bad = ~np.isfinite(out)
        if bad.any():
            out[bad] = np.asarray(drawn, dtype=float)[bad]
        return out

    def _encode_block(self, df: pd.DataFrame, cols: list[str]) -> np.ndarray:
        if not cols:
            return np.empty((len(df), 0), dtype=float)
        mats: list[np.ndarray] = []
        for col in cols:
            if self.kinds_[col] == "cat":
                raw = self._encode_categorical(df[col], col)
                mean = self.cat_mean_.get(col, 0.0)
                scale = self.cat_scale_.get(col, 1.0)
                mats.append((raw - mean) / scale)
            else:
                numeric = pd.to_numeric(pd.Series(df[col].to_numpy()), errors="coerce")
                filled = numeric.fillna(self.num_fill_[col]).to_numpy(dtype=float)
                filled = np.where(np.isfinite(filled), filled, self.num_fill_[col])
                mean = self.num_mean_.get(col, 0.0)
                scale = self.num_scale_.get(col, 1.0)
                mats.append((filled - mean) / scale)
        return np.column_stack(mats)

    def _encode_categorical(self, series: pd.Series, col: str) -> np.ndarray:
        cats = self.cat_categories_[col]
        fill = self.cat_fill_[col]
        fill_code = _category_code(fill, cats) if fill is not None else -1
        values = series.to_numpy()
        if _is_bool_like(cats) or _is_bool_dtype(self.dtypes_.get(col)):
            norm_cats = [bool(c) for c in cats]
            norm_vals: list[Any] = []
            for v in values:
                if _is_na(v):
                    norm_vals.append(None)
                else:
                    norm_vals.append(bool(v))
            cat = pd.Categorical(norm_vals, categories=norm_cats)
        else:
            cat = pd.Categorical(values, categories=list(cats))
        codes = cat.codes.astype(float)
        if fill_code >= 0:
            codes = np.where(codes < 0, float(fill_code), codes)
        else:
            codes = np.where(codes < 0, 0.0, codes)
        return codes

    def _cast_column(self, col: str, values: np.ndarray) -> Any:
        dtype = self.dtypes_[col]
        if self.kinds_[col] == "cat":
            cats = self.cat_categories_.get(col)
            if _is_bool_dtype(dtype):
                return np.asarray([bool(v) if not _is_na(v) else False for v in values])
            if isinstance(dtype, pd.CategoricalDtype):
                return pd.Categorical(values, categories=dtype.categories)
            if cats is not None and pd.api.types.is_integer_dtype(dtype):
                arr = np.array([int(v) for v in values], dtype=np.int64)
                try:
                    return arr.astype(dtype, copy=False)
                except (TypeError, ValueError):
                    return arr
            if pd.api.types.is_object_dtype(dtype) or pd.api.types.is_string_dtype(dtype):
                return np.asarray(values, dtype=object)
            return values
        arr = np.asarray(values, dtype=float)
        if pd.api.types.is_integer_dtype(dtype):
            rounded = np.rint(arr)
            try:
                return rounded.astype(dtype, copy=False)
            except (TypeError, ValueError):
                return rounded.astype(np.int64, copy=False)
        return arr


def synthesize_knn(
    df: pd.DataFrame,
    n: int | None = None,
    seed: int = 0,
    include_targets: bool = True,
    n_neighbors: int = 15,
    jitter: float = 0.25,
) -> pd.DataFrame:
    """Fit a sequential kNN synthesizer and draw ``n`` rows (default ``len(df)``)."""
    if n is None:
        n = len(df)
    synth = KNNConditionalSynthesizer()
    synth.fit(
        df,
        include_targets=include_targets,
        n_neighbors=n_neighbors,
        jitter=jitter,
    )
    return synth.sample(int(n), seed=seed)


# Discovery aliases used by auto / multi-dataset loaders.
KNNSynthesizer = KNNConditionalSynthesizer
KnnSynthesizer = KNNConditionalSynthesizer
NearestNeighborSynthesizer = KNNConditionalSynthesizer
synthesize_nearest_neighbor = synthesize_knn


def _self_test() -> pd.DataFrame:
    """Exercise a generic mixed schema — no domain-specific column names."""
    rng = np.random.default_rng(11)
    n = 280
    grp = rng.choice(["a", "b", "c"], size=n, p=[0.5, 0.3, 0.2])
    hue = rng.choice(["red", "blue"], size=n)
    z0 = rng.normal(0.0, 1.0, size=n)
    z1 = np.empty(n)
    for i in range(n):
        if grp[i] == "a":
            z1[i] = 0.9 * z0[i] + rng.normal(0.0, 0.25)
        elif grp[i] == "b":
            z1[i] = -0.8 * z0[i] + rng.normal(0.0, 0.25)
        else:
            z1[i] = rng.normal(0.0, 1.0)
    n_items = rng.integers(0, 6, size=n, dtype=np.int64)
    on = rng.integers(0, 2, size=n).astype(bool)
    y = 1.4 * z0 * z1 + 0.25 * n_items + rng.normal(0.0, 0.35, size=n)
    y_class = (y > np.median(y)).astype(np.int64)

    df = pd.DataFrame(
        {
            "grp": grp,
            "hue": pd.Categorical(hue, categories=["red", "blue"]),
            "z0": z0,
            "z1": z1,
            "n_items": n_items,
            "on": on,
            "y": y,
            "y_class": y_class,
        }
    )
    miss = rng.choice(n, size=8, replace=False)
    df.loc[miss[:4], "z0"] = np.nan
    df.loc[miss[4:], "hue"] = np.nan

    n_synth = 120
    synth = KNNConditionalSynthesizer()
    fitted = synth.fit(df, include_targets=True, n_neighbors=15)
    if fitted is not synth:
        raise AssertionError("fit() must return self")
    out = synth.sample(n_synth, seed=0)
    if len(out) != n_synth:
        raise AssertionError(f"expected {n_synth} rows, got {len(out)}")
    if list(out.columns) != list(df.columns):
        raise AssertionError(f"column mismatch: {list(out.columns)}")
    if out["grp"].nunique(dropna=True) < 2:
        raise AssertionError("grp collapsed")
    if out["hue"].nunique(dropna=True) < 2:
        raise AssertionError("hue collapsed")
    if not pd.api.types.is_bool_dtype(out["on"].dtype):
        raise AssertionError("bool column lost dtype")
    if list(out["hue"].cat.categories) != ["red", "blue"]:
        raise AssertionError("categorical levels not restored")

    real_a = df.loc[df["grp"] == "a", ["z0", "z1"]].dropna()
    syn_a = out.loc[out["grp"] == "a", ["z0", "z1"]].dropna()
    if len(real_a) >= 20 and len(syn_a) >= 20:
        r_real = float(np.corrcoef(real_a.to_numpy().T)[0, 1])
        r_syn = float(np.corrcoef(syn_a.to_numpy().T)[0, 1])
        if not np.isfinite(r_syn) or r_real * r_syn <= 0:
            raise AssertionError(
                f"group-a corr sign lost (real={r_real:.3f}, syn={r_syn:.3f})"
            )

    helper = synthesize_knn(df, n=40, seed=2, include_targets=True)
    if list(helper.columns) != list(df.columns) or len(helper) != 40:
        raise AssertionError("synthesize_knn helper failed")

    no_tgt = synthesize_knn(df, n=30, seed=3, include_targets=False)
    if "y" in no_tgt.columns or "y_class" in no_tgt.columns:
        raise AssertionError("include_targets=False should drop y / y_class")
    if set(no_tgt.columns) != set(df.columns) - {"y", "y_class"}:
        raise AssertionError("include_targets=False dropped unexpected columns")

    empty = synth.sample(0, seed=4)
    if len(empty) != 0 or list(empty.columns) != list(df.columns):
        raise AssertionError("n=0 sample failed")

    tiny = df.head(6).reset_index(drop=True)
    tiny_out = synthesize_knn(tiny, n=12, seed=5, include_targets=True, n_neighbors=15)
    if len(tiny_out) != 12:
        raise AssertionError("k > n_train path failed")

    single = synthesize_knn(df[["z0"]], n=16, seed=6)
    if list(single.columns) != ["z0"] or len(single) != 16:
        raise AssertionError("single-column path failed")

    other = pd.DataFrame(
        {
            "alpha": rng.normal(size=90),
            "beta": rng.choice(list("xyz"), size=90),
            "gamma": rng.integers(0, 4, size=90, dtype=np.int64),
        }
    )
    other_out = synthesize_knn(other, n=25, seed=7)
    if list(other_out.columns) != ["alpha", "beta", "gamma"] or len(other_out) != 25:
        raise AssertionError("alternate generic schema failed")

    const = pd.DataFrame({"alpha": np.ones(20), "beta": rng.normal(size=20)})
    const_out = KNNConditionalSynthesizer().fit(const, n_neighbors=5).sample(10, seed=8)
    if not np.allclose(const_out["alpha"].to_numpy(dtype=float), 1.0):
        raise AssertionError("constant column not reproduced")

    return out


if __name__ == "__main__":
    sample = _self_test()
    print(
        "self-test ok:",
        f"{len(sample)} rows,",
        f"columns={list(sample.columns)}",
    )
    print(
        "API: KNNConditionalSynthesizer.fit(df, include_targets=True, "
        "n_neighbors=15); .sample(n, seed) | "
        "synthesize_knn(df, n=None, seed=0, include_targets=True)"
    )
    print(
        "Failure modes: curse of dimensionality (distance concentration "
        "in the encoded previous-col space → later conditionals, including "
        "y / y_class, collapse toward the marginal); k≈n oversmoothing; "
        "exact donor copies when jitter=0; ordinal codes for nominal cats; "
        "imputed missingness."
    )
